insert into settings (key_name, value, updated_at) values
('about_us', 'AIMEDIX MEDS connects local customers with commerce, mart, medical, services, hotel, restaurant and real estate partners through one city platform.', current_timestamp),
('terms_conditions', 'Orders and bookings are subject to stock, zone coverage, partner availability, price verification, payment verification, prescription review where applicable and operational feasibility. Misuse of refunds, wallets, coupons, complaints, prescriptions, reviews or support tools may lead to rejection, reversal, cancellation or account restrictions.', current_timestamp),
('privacy_policy', 'AIMEDIX MEDS uses account, address, location, order, booking, payment reference, wallet, support, complaint, prescription and device-token data to operate the platform, process transactions, route services, prevent fraud, provide support and comply with law. Data may be shared with relevant vendors, providers, hotels, restaurants, agents, payment providers, notification providers and legal authorities where required. We do not sell personal or sensitive user data.', current_timestamp),
('refund_policy', 'Refunds and cancellations are reviewed by admin according to order or booking status, payment status, product or service type, partner policy, customer evidence and applicable law. Approved refunds may be credited to wallet or original payment method depending on payment configuration and reconciliation.', current_timestamp),
('shipping_policy', 'Delivery, service and booking timelines depend on zone coverage, partner capacity, stock, route conditions, customer availability, weather, payment verification and operational constraints. Taxes, delivery charges, service charges and partner-specific rules may apply.', current_timestamp),
('support_content', 'Use support, chat or complaint options with the correct order/booking number, evidence and contact details. Abuse, false claims or unsafe content may be restricted.', current_timestamp),
('medical.terms_conditions', 'Medicine orders are subject to prescription validation, pharmacy/admin review, stock, quantity limits, age confirmation where required, zone availability and applicable pharmacy law. Restricted, habit-forming, narcotic, psychotropic, Schedule H/H1/X-like or unsafe online-sale products may be rejected or blocked.', current_timestamp),
('medical.privacy_policy', 'Prescription images and medical order details are sensitive information and are used only for prescription review, medicine fulfillment, support, dispute handling, safety checks and legally required records. Access should be limited to authorized pharmacy/admin personnel.', current_timestamp),
('medical.refund_policy', 'Prescription medicines, opened products, cold-chain products, hygiene-sensitive products, restricted medicines and correctly supplied medicines may be non-returnable except where required by law or where the wrong, damaged, expired or unsafe item was supplied.', current_timestamp),
('medical.prescription_policy', 'Prescription-required medicines are fulfilled only after valid prescription upload and pharmacist/admin approval. Invalid, altered, mismatched, expired or suspicious prescriptions may be rejected and the order may be cancelled or escalated.', current_timestamp),
('services.terms_conditions', 'Service bookings are subject to provider availability, slot capacity, zone coverage, customer contactability, payment verification and admin/provider confirmation. Reschedules, cancellation requests and service changes may require provider/admin approval.', current_timestamp),
('services.refund_policy', 'Service refunds depend on booking status, cancellation window, provider travel/material cost, work already started, evidence and admin/provider review. No-shows, late cancellations or started work may be partially or fully non-refundable.', current_timestamp),
('services.shipping_policy', 'Service arrival and completion timelines depend on provider availability, zone coverage, traffic, materials, customer access and booking complexity.', current_timestamp),
('hotel.terms_conditions', 'Hotel bookings are subject to room availability, rate plan, guest details, check-in rules, payment verification, hotel-owner confirmation, taxes and applicable property policy.', current_timestamp),
('hotel.refund_policy', 'Hotel cancellation and refund depend on free cancellation window, check-in date, rate plan, no-show status, hotel policy and admin/hotel-owner confirmation. Late cancellations may be partially or fully non-refundable.', current_timestamp),
('restaurant.terms_conditions', 'Restaurant reservations and waitlist requests are subject to restaurant availability, table capacity, party size, zone coverage, deposit/payment rules where configured and restaurant/admin confirmation.', current_timestamp),
('restaurant.refund_policy', 'Restaurant booking fees, deposits, no-show charges and late cancellations may be partially or fully non-refundable according to restaurant/admin policy.', current_timestamp),
('real_estate.terms_conditions', 'Real estate listings, site visits, inquiries and saved searches are informational and subject to project/agent availability, verification, price changes and legal/property due diligence by the user.', current_timestamp),
('real_estate.privacy_policy', 'Real estate inquiries and site visit details may be shared with relevant agents, project owners or admin staff to schedule visits, respond to leads and provide support.', current_timestamp)
on duplicate key update
value = values(value),
updated_at = current_timestamp;
