const clouthingProduct = [
  {
    id: 11,
    title: 'Urban Cotton Tee',
    name: 'Urban Cotton Tee',
    description: 'Soft breathable everyday tee crafted for comfort and easy styling.',
    rating: 4.3,
    price: 19944,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing1.png',
    category: 'Clothing',
    brand: 'UrbanX',
    stock: 50,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 12,
    title: 'Relaxed Denim Jacket',
    name: 'Relaxed Denim Jacket',
    description: 'Classic jacket with durable fabric and a timeless casual look.',
    rating: 4.1,
    price: 47234,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing2.png',
    category: 'Clothing',
    brand: 'Prime',
    stock: 67,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 13,
    title: 'Athleisure Jogger Set',
    name: 'Athleisure Jogger Set',
    description: 'Stretch-fit comfort for workouts, travel, and everyday wear.',
    rating: 4.9,
    price: 18033,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing3.png',
    category: 'Clothing',
    brand: 'ProMax',
    stock: 14,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 14,
    title: 'Classic Hoodie',
    name: 'Classic Hoodie',
    description: 'Cozy fleece hoodie with a modern silhouette and premium feel.',
    rating: 4.3,
    price: 41478,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing4.png',
    category: 'Clothing',
    brand: 'Nova',
    stock: 100,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 15,
    title: 'Linen Summer Shirt',
    name: 'Linen Summer Shirt',
    description: 'Lightweight and airy shirt designed for warm weather and relaxed dressing.',
    rating: 4.6,
    price: 21683,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing5.png',
    category: 'Clothing',
    brand: 'Elite',
    stock: 54,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 16,
    title: 'Performance Running Shorts',
    name: 'Performance Running Shorts',
    description: 'Flexible shorts with moisture-wicking fabric for active days.',
    rating: 4.0,
    price: 36250,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing6.png',
    category: 'Clothing',
    brand: 'ProMax',
    stock: 48,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 17,
    title: 'Wool Knit Sweater',
    name: 'Wool Knit Sweater',
    description: 'Warm textured sweater that adds comfort and elegance to cooler outfits.',
    rating: 4.3,
    price: 4986,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing7.png',
    category: 'Clothing',
    brand: 'Prime',
    stock: 27,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 18,
    title: 'Travel Carry-On Backpack',
    name: 'Travel Carry-On Backpack',
    description: 'Spacious everyday backpack built for convenience and organization.',
    rating: 4.2,
    price: 32554,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing8.png',
    category: 'Clothing',
    brand: 'ProMax',
    stock: 55,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 19,
    title: 'Minimalist Leather Belt',
    name: 'Minimalist Leather Belt',
    description: 'Refined accessory with a clean finish and durable construction.',
    rating: 4.3,
    price: 45870,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing9.png',
    category: 'Clothing',
    brand: 'ProMax',
    stock: 84,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 20,
    title: 'Soft Knit Cap',
    name: 'Soft Knit Cap',
    description: 'Stretchable cap designed for comfort and everyday outdoor use.',
    rating: 4.2,
    price: 31642,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/Clothing/Clothing10.png',
    category: 'Clothing',
    brand: 'Nova',
    stock: 12,
    delivery: '2-5 Days',
    size: ['S', 'M', 'L', 'XL'],
    color: ['Black', 'White', 'Blue']
  }
];

export default clouthingProduct