const electricalproduct = [
  {
    id: 1,
    title: 'UltraLite Laptop',
    name: 'UltraLite Laptop',
    description: 'A slim and powerful laptop for work, study, and entertainment with crisp display and all-day battery life.',
    rating: 4.5,
    price: 43647,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem1.png',
    category: 'Electronics',
    brand: 'Prime',
    stock: 32,
    delivery: '2-5 Days'
  },
  {
    id: 2,
    title: 'Smart 4K LED TV',
    name: 'Smart 4K LED TV',
    description: 'Immersive entertainment with vivid colors, smart streaming, and a sleek modern design.',
    rating: 4.1,
    price: 33620,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem2.png',
    category: 'Electronics',
    brand: 'Nova',
    stock: 5,
    delivery: '2-5 Days'
  },
  {
    id: 3,
    title: 'Wireless Noise-Canceling Headphones',
    name: 'Wireless Noise-Canceling Headphones',
    description: 'Comfortable audio experience with rich bass and seamless Bluetooth connectivity.',
    rating: 4.4,
    price: 18872,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem3.png',
    category: 'Electronics',
    brand: 'Prime',
    stock: 22,
    delivery: '2-5 Days'
  },
  {
    id: 4,
    title: 'Portable Bluetooth Speaker',
    name: 'Portable Bluetooth Speaker',
    description: 'Compact yet powerful speaker with deep sound and durable build for travel and gatherings.',
    rating: 4.3,
    price: 3696,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem4.png',
    category: 'Electronics',
    brand: 'Elite',
    stock: 63,
    delivery: '2-5 Days'
  },
  {
    id: 5,
    title: 'Ergonomic Gaming Mouse',
    name: 'Ergonomic Gaming Mouse',
    description: 'Precision tracking and responsive clicking for smooth gaming and productive everyday use.',
    rating: 4.1,
    price: 508,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem5.png',
    category: 'Electronics',
    brand: 'ProMax',
    stock: 23,
    delivery: '2-5 Days'
  },
  {
    id: 6,
    title: 'Smart Fitness Watch',
    name: 'Smart Fitness Watch',
    description: 'Track your activity, sleep, and heart rate in style with this lightweight smartwatch.',
    rating: 4.6,
    price: 43193,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem6.png',
    category: 'Electronics',
    brand: 'Elite',
    stock: 51,
    delivery: '2-5 Days'
  },
  {
    id: 7,
    title: 'Fast-Charging Power Bank',
    name: 'Fast-Charging Power Bank',
    description: 'Reliable backup power for your devices when you are on the move.',
    rating: 4.2,
    price: 39278,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem7.png',
    category: 'Electronics',
    brand: 'UrbanX',
    stock: 91,
    delivery: '2-5 Days'
  },
  {
    id: 8,
    title: 'Slim Mechanical Keyboard',
    name: 'Slim Mechanical Keyboard',
    description: 'A tactile, quiet keyboard designed for fast typing and clean desk setup.',
    rating: 4.1,
    price: 37790,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem8.png',
    category: 'Electronics',
    brand: 'UrbanX',
    stock: 96,
    delivery: '2-5 Days'
  },
  {
    id: 9,
    title: 'Pocket Camera Drone',
    name: 'Pocket Camera Drone',
    description: 'Capture cinematic aerial shots with easy controls and stable flight performance.',
    rating: 4.6,
    price: 31002,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem9.png',
    category: 'Electronics',
    brand: 'ProMax',
    stock: 71,
    delivery: '2-5 Days'
  },
  {
    id: 10,
    title: 'USB-C Wall Charger',
    name: 'USB-C Wall Charger',
    description: 'Compact charger with multi-port support for quick and safe charging.',
    rating: 4.4,
    price: 11893,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/electricalItem/electricalItem10.png',
    category: 'Electronics',
    brand: 'Prime',
    stock: 77,
    delivery: '2-5 Days'
  }
];

export default electricalproduct