const footwearProduct = [
  {
    id: 21,
    title: 'Cloud Runner Sneakers',
    name: 'Cloud Runner Sneakers',
    description: 'Lightweight sneakers designed for all-day comfort and smooth movement.',
    rating: 4.3,
    price: 28550,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear1.png',
    category: 'Footwear',
    brand: 'UrbanX',
    stock: 80,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 22,
    title: 'TrailFlex Hiking Boots',
    name: 'TrailFlex Hiking Boots',
    description: 'Durable boots with strong grip for rocky trails and outdoor adventures.',
    rating: 4.1,
    price: 42749,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear2.png',
    category: 'Footwear',
    brand: 'Prime',
    stock: 88,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 23,
    title: 'Aero Court Shoes',
    name: 'Aero Court Shoes',
    description: 'Modern court shoes offering support and style for active days.',
    rating: 4.8,
    price: 13118,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear3.png',
    category: 'Footwear',
    brand: 'Elite',
    stock: 31,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 24,
    title: 'Desert Sandals',
    name: 'Desert Sandals',
    description: 'Breathable sandals built for comfort during warm weather and casual outings.',
    rating: 4.3,
    price: 5868,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear4.png',
    category: 'Footwear',
    brand: 'Elite',
    stock: 15,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 25,
    title: 'Urban Slip-Ons',
    name: 'Urban Slip-Ons',
    description: 'Easy-to-wear shoes with a sleek profile for everyday errands.',
    rating: 4.9,
    price: 48322,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear5.png',
    category: 'Footwear',
    brand: 'Elite',
    stock: 80,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 26,
    title: 'Elite Running Shoes',
    name: 'Elite Running Shoes',
    description: 'Responsive cushioning and stable support for daily runs and training.',
    rating: 4.7,
    price: 24898,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear6.png',
    category: 'Footwear',
    brand: 'ProMax',
    stock: 74,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 27,
    title: 'Winter Snow Boots',
    name: 'Winter Snow Boots',
    description: 'Insulated boots made to keep your steps warm and steady.',
    rating: 4.5,
    price: 27379,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear7.png',
    category: 'Footwear',
    brand: 'Nova',
    stock: 15,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 28,
    title: 'Classic Loafers',
    name: 'Classic Loafers',
    description: 'Polished loafers that balance comfort with timeless style.',
    rating: 4.7,
    price: 15930,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear8.png',
    category: 'Footwear',
    brand: 'Nova',
    stock: 44,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 29,
    title: 'Sporty Training Flats',
    name: 'Sporty Training Flats',
    description: 'Flexible flats ideal for movement, walking, and comfortable daily wear.',
    rating: 4.1,
    price: 44608,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear9.png',
    category: 'Footwear',
    brand: 'Elite',
    stock: 68,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  },
  {
    id: 30,
    title: 'Ridge Trek Sandals',
    name: 'Ridge Trek Sandals',
    description: 'Adventure-ready sandals with strong grip and durable design.',
    rating: 4.1,
    price: 44411,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/Footwear/Footwear10.png',
    category: 'Footwear',
    brand: 'ProMax',
    stock: 86,
    delivery: '2-5 Days',
    size: [6, 7, 8, 9, 10],
    color: ['Black', 'White', 'Blue']
  }
];

export default footwearProduct