const kitchenProduct = [
  {
    id: 31,
    title: 'Ceramic Mixing Bowl Set',
    name: 'Ceramic Mixing Bowl Set',
    description: 'Elegant and practical bowls for prep, serving, and everyday cooking.',
    rating: 4.7,
    price: 15012,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems1.png',
    category: 'Home & Kitchen',
    brand: 'UrbanX',
    stock: 9,
    delivery: '2-5 Days'
  },
  {
    id: 32,
    title: 'Stainless Steel Blender',
    name: 'Stainless Steel Blender',
    description: 'Powerful blending performance for smoothies, soups, and sauces.',
    rating: 4.8,
    price: 46641,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems2.png',
    category: 'Home & Kitchen',
    brand: 'Nova',
    stock: 14,
    delivery: '2-5 Days'
  },
  {
    id: 33,
    title: 'Copper Cookware Pan',
    name: 'Copper Cookware Pan',
    description: 'Premium pan with even heat distribution for precise cooking.',
    rating: 4.7,
    price: 5146,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems3.png',
    category: 'Home & Kitchen',
    brand: 'Elite',
    stock: 50,
    delivery: '2-5 Days'
  },
  {
    id: 34,
    title: 'Glass Food Storage Jar',
    name: 'Glass Food Storage Jar',
    description: 'Airtight jars that keep ingredients fresh and organized.',
    rating: 4.0,
    price: 38559,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems4.png',
    category: 'Home & Kitchen',
    brand: 'ProMax',
    stock: 25,
    delivery: '2-5 Days'
  },
  {
    id: 35,
    title: 'Nonstick Frying Pan',
    name: 'Nonstick Frying Pan',
    description: 'Durable cookware designed for effortless cooking and easy cleanup.',
    rating: 4.3,
    price: 18002,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems5.png',
    category: 'Home & Kitchen',
    brand: 'ProMax',
    stock: 44,
    delivery: '2-5 Days'
  },
  {
    id: 36,
    title: 'Wooden Serving Tray',
    name: 'Wooden Serving Tray',
    description: 'Handcrafted tray that brings warmth and style to your table.',
    rating: 4.7,
    price: 28418,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems6.png',
    category: 'Home & Kitchen',
    brand: 'Nova',
    stock: 6,
    delivery: '2-5 Days'
  },
  {
    id: 37,
    title: 'Electric Kettle',
    name: 'Electric Kettle',
    description: 'Fast boiling and energy-efficient kettle for tea, coffee, and instant meals.',
    rating: 4.5,
    price: 31145,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems7.png',
    category: 'Home & Kitchen',
    brand: 'ProMax',
    stock: 37,
    delivery: '2-5 Days'
  },
  {
    id: 38,
    title: 'Cutlery Set',
    name: 'Cutlery Set',
    description: 'Modern cutlery designed for comfortable daily dining and hosting.',
    rating: 4.7,
    price: 19439,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems8.png',
    category: 'Home & Kitchen',
    brand: 'Prime',
    stock: 46,
    delivery: '2-5 Days'
  },
  {
    id: 39,
    title: 'Food Processor',
    name: 'Food Processor',
    description: 'Versatile kitchen assistant for chopping, slicing, and mixing with ease.',
    rating: 4.5,
    price: 41203,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems9.png',
    category: 'Home & Kitchen',
    brand: 'Elite',
    stock: 74,
    delivery: '2-5 Days'
  },
  {
    id: 40,
    title: 'Insulated Coffee Mug',
    name: 'Insulated Coffee Mug',
    description: 'A sturdy mug that keeps drinks hot while feeling comfortable in hand.',
    rating: 4.7,
    price: 42228,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/KitchenItems/KitchenItems10.png',
    category: 'Home & Kitchen',
    brand: 'ProMax',
    stock: 30,
    delivery: '2-5 Days'
  }
];


export default kitchenProduct