const booksProduct = [
  {
    id: 41,
    title: 'The Silver Compass',
    name: 'The Silver Compass',
    description: 'An adventurous tale of discovery, courage, and finding your way home.',
    rating: 4.3,
    price: 17106,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/book/books1.png',
    category: 'Books',
    brand: 'ProMax',
    stock: 98,
    delivery: '2-5 Days'
  },
  {
    id: 42,
    title: 'Neon Horizon',
    name: 'Neon Horizon',
    description: 'A fast-paced sci-fi journey through glowing cities and impossible dreams.',
    rating: 4.1,
    price: 905,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/book/books2.png',
    category: 'Books',
    brand: 'ProMax',
    stock: 49,
    delivery: '2-5 Days'
  },
  {
    id: 43,
    title: 'Moonlit Algorithms',
    name: 'Moonlit Algorithms',
    description: 'A thoughtful mystery blending code, logic, and midnight secrets.',
    rating: 4.7,
    price: 9519,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/book/books3.png',
    category: 'Books',
    brand: 'ProMax',
    stock: 40,
    delivery: '2-5 Days'
  },
  {
    id: 44,
    title: 'Echoes of Tomorrow',
    name: 'Echoes of Tomorrow',
    description: 'A reflective novel about memory, choice, and the future we create.',
    rating: 4.3,
    price: 35187,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/book/books4.png',
    category: 'Books',
    brand: 'Prime',
    stock: 88,
    delivery: '2-5 Days'
  },
  {
    id: 45,
    title: 'Paper Gardens',
    name: 'Paper Gardens',
    description: 'A poetic story about healing, nature, and quiet resilience.',
    rating: 4.2,
    price: 33041,
    offer: '20% OFF',
    image: 'http://localhost:4876/product/book/books5.png',
    category: 'Books',
    brand: 'UrbanX',
    stock: 42,
    delivery: '2-5 Days'
  },
  {
    id: 46,
    title: 'The Quiet Fire',
    name: 'The Quiet Fire',
    description: 'A gripping drama of passion, loss, and personal transformation.',
    rating: 4.4,
    price: 19235,
    offer: '30% OFF',
    image: 'http://localhost:4876/product/book/books6.png',
    category: 'Books',
    brand: 'Elite',
    stock: 80,
    delivery: '2-5 Days'
  },
  {
    id: 47,
    title: 'Atlas of Forgotten Stars',
    name: 'Atlas of Forgotten Stars',
    description: 'An imaginative fantasy tale of lost worlds and ancient maps.',
    rating: 4.5,
    price: 14099,
    offer: '15% OFF',
    image: 'http://localhost:4876/product/book/books7.png',
    category: 'Books',
    brand: 'Elite',
    stock: 86,
    delivery: '2-5 Days'
  },
  {
    id: 48,
    title: 'Cinnamon Rain',
    name: 'Cinnamon Rain',
    description: 'A warm-hearted story of love, family, and second chances.',
    rating: 4.4,
    price: 30940,
    offer: '25% OFF',
    image: 'http://localhost:4876/product/book/books8.png',
    category: 'Books',
    brand: 'Prime',
    stock: 44,
    delivery: '2-5 Days'
  },
  {
    id: 49,
    title: 'The Midnight Ledger',
    name: 'The Midnight Ledger',
    description: 'A clever suspense novel filled with secrets and sharp twists.',
    rating: 4.3,
    price: 4421,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/book/books9.png',
    category: 'Books',
    brand: 'Nova',
    stock: 24,
    delivery: '2-5 Days'
  },
  {
    id: 50,
    title: 'Bright River Notes',
    name: 'Bright River Notes',
    description: 'An inspiring memoir of travel, reflection, and new beginnings.',
    rating: 4.3,
    price: 43675,
    offer: '10% OFF',
    image: 'http://localhost:4876/product/book/books10.png',
    category: 'Books',
    brand: 'Nova',
    stock: 52,
    delivery: '2-5 Days'
  }
];

export default booksProduct