<?php $browserMapsKey = trim((string) ($publicSettings['google_maps_browser_api_key'] ?? '')); ?>
<main class="web-app" id="medical-web-app" data-maps-enabled="<?= $browserMapsKey !== '' ? '1' : '0' ?>">
  <section class="web-app-header">
    <div><span class="pill">AIMEDIX healthcare store</span><h1>Care, tests and medicines <br>in one place.</h1><p>Choose your service area, then shop or book from verified healthcare partners.</p></div>
    <div class="web-actions"><button class="btn btn-outline" id="web-location-button" type="button">Choose location</button><button class="btn btn-orange" id="web-account-button" type="button">Sign in</button></div>
  </section>
  <div id="web-global-status" aria-live="polite"></div>
  <nav class="web-tabs" aria-label="Healthcare store sections">
    <button class="web-tab active" data-tab="medicines">Medicines</button>
    <button class="web-tab" data-tab="labs">Lab tests</button>
    <button class="web-tab" data-tab="doctors">Doctors</button>
    <button class="web-tab" data-tab="prescriptions">Prescriptions</button>
    <button class="web-tab" data-tab="orders">My activity</button>
    <button class="web-tab" data-tab="messages">Messages</button>
    <button class="web-tab" data-tab="notifications">Notifications</button>
    <button class="web-tab" data-tab="account">My account</button>
  </nav>

  <section class="web-panel active" data-panel="medicines">
    <div class="web-toolbar"><input id="web-product-search" type="search" placeholder="Search medicines and healthcare products"><select id="web-category-filter"><option value="">All categories</option></select><button class="btn btn-dark" id="web-search-button" type="button">Search</button></div>
    <div class="web-grid" id="web-products"><div class="web-empty">Loading medicines…</div></div>
  </section>
  <section class="web-panel" data-panel="labs"><h2>Lab tests</h2><p>Book a centre visit or home sample collection.</p><div class="web-grid" id="web-labs"></div></section>
  <section class="web-panel" data-panel="doctors"><h2>Doctor consultations</h2><p>Choose online or clinic consultation with an approved doctor.</p><div class="web-grid" id="web-doctors"></div></section>
  <section class="web-panel" data-panel="prescriptions">
    <div class="web-card" style="max-width:760px"><h2>Upload a prescription</h2><p>A pharmacy reviews the document and sends an itemised quote. You approve the exact total before checkout.</p>
      <form id="web-prescription-form" style="display:grid;gap:12px"><input name="prescription" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required><textarea name="note" placeholder="Notes for the pharmacist (optional)"></textarea><select name="substitution_preference"><option value="contact_me">Contact me before substitution</option><option value="allow">Allow equivalent substitutes</option><option value="no_substitution">No substitutions</option></select><button class="btn btn-dark" type="submit">Send for pharmacist review</button></form>
    </div><h2 style="margin-top:28px">My prescription requests</h2><div id="web-prescriptions"></div>
  </section>
  <section class="web-panel" data-panel="orders"><div class="web-row"><h2>Orders and appointments</h2><button class="btn btn-outline" id="web-refresh-activity" type="button">Refresh</button></div><div id="web-orders"></div><h3>Lab bookings</h3><div id="web-lab-bookings"></div><h3>Consultations</h3><div id="web-consultations"></div></section>
  <section class="web-panel" data-panel="messages"><div class="web-row"><div><h2>Healthcare messages</h2><p>Conversations with your pharmacy, laboratory or doctor.</p></div><button class="btn btn-outline" id="web-refresh-messages">Refresh</button></div><div id="web-messages"></div></section>
  <section class="web-panel" data-panel="notifications"><div class="web-row"><div><h2>Notifications</h2><p>Order, prescription and appointment updates.</p></div><button class="btn btn-outline" id="web-read-notifications">Mark all read</button></div><div id="web-notifications"></div><h2 style="margin-top:28px">Refund requests</h2><div id="web-refunds"></div></section>
  <section class="web-panel" data-panel="account"><div id="web-account"></div></section>

  <button class="btn btn-orange cart-float" id="web-cart-button" type="button">View cart · <span id="web-cart-count">0</span> <span id="web-cart-item-label">items</span> · ₹<span id="web-cart-total">0</span></button>
</main>

<dialog class="web-dialog" id="web-auth-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Customer account</h2><button class="icon-button" data-close type="button">×</button></div><div class="web-tabs" style="position:static"><button class="web-tab active" data-auth-mode="login">Sign in</button><button class="web-tab" data-auth-mode="register">Create account</button></div><form id="web-auth-form" style="display:grid;gap:12px"><label data-register-only hidden>Full name<input name="name" autocomplete="name"></label><label>Phone number<input name="phone" inputmode="tel" autocomplete="tel" required></label><label data-register-only hidden>Email (optional)<input name="email" type="email" autocomplete="email"></label><label>Password<input name="password" type="password" minlength="6" autocomplete="current-password" required></label><div id="web-auth-status"></div><button class="btn btn-dark" type="submit">Sign in</button></form></div></dialog>

<dialog class="web-dialog" id="web-location-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Select service location</h2><button class="icon-button" data-close type="button">×</button></div><?php if ($browserMapsKey === ''): ?><div class="web-status error">Website Maps is not configured. Add the browser Maps key in Admin → Settings → Medical.</div><?php else: ?><div class="web-toolbar"><input id="customer-map-search" placeholder="Search locality or landmark"><button class="btn btn-outline" id="customer-map-search-button" type="button">Search</button><button class="btn btn-outline" id="customer-current-location" type="button">Use current location</button></div><div id="customer-map" style="height:330px;border-radius:18px"></div><div id="customer-location-status" class="web-status">Tap the map to choose your exact location.</div><button class="btn btn-dark" id="customer-confirm-location" disabled type="button">Use this service area</button><?php endif; ?></div></dialog>

<dialog class="web-dialog" id="web-address-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Complete delivery address</h2><button class="icon-button" data-close type="button">×</button></div><form id="web-address-form" style="display:grid;grid-template-columns:1fr 1fr;gap:12px"><label style="grid-column:1/-1">House / flat and building<input name="house" required></label><label>Floor (optional)<input name="floor"></label><label>Street / area<input name="area" required></label><label style="grid-column:1/-1">Landmark (optional)<input name="landmark"></label><label>Label<select name="label"><option>Home</option><option>Work</option><option>Other</option></select></label><label>PIN code<input name="pincode" required></label><button class="btn btn-dark" style="grid-column:1/-1" type="submit">Save address</button></form></div></dialog>

<dialog class="web-dialog" id="web-cart-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Your cart</h2><button class="icon-button" data-close type="button">×</button></div><div id="web-cart-items"></div><label>Delivery address<select id="web-checkout-address"></select></label><button class="btn btn-outline" id="web-add-address" type="button">Add another address</button><label>Prescription when required<input id="web-order-prescription" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"></label><label>Payment method<select id="web-payment-method"></select></label><label id="web-payment-reference-wrap" hidden>Payment / transaction reference<input id="web-payment-reference" placeholder="Reference number"></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:flex-start"><input id="web-age-confirmed" type="checkbox" style="width:auto;margin-top:4px"> I confirm that the patient/customer meets applicable age requirements and the provided information is correct.</label><div id="web-checkout-status"></div><button class="btn btn-dark" id="web-place-order" type="button">Place order</button></div></dialog>

<dialog class="web-dialog" id="web-book-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2 id="web-book-title">Book service</h2><button class="icon-button" data-close type="button">×</button></div><form id="web-book-form" style="display:grid;gap:12px"><input name="entity_id" type="hidden"><input name="kind" type="hidden"><label>Date and time<input name="scheduled_at" type="datetime-local" required></label><label id="web-book-mode-label">Mode<select name="mode"></select></label><label>Reason / notes<textarea name="reason"></textarea></label><label>Payment<select name="payment_method"><option value="cash_on_delivery">Cash / pay at service</option><option value="bank_transfer">Bank transfer</option></select></label><button class="btn btn-dark" type="submit">Confirm booking</button></form></div></dialog>
<dialog class="web-dialog" id="web-order-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2 id="web-order-title">Order details</h2><button class="icon-button" data-close type="button">×</button></div><div id="web-order-eta" class="web-status"></div><div id="web-order-map" style="height:330px;border-radius:18px;background:#edf4f9"></div><div id="web-order-details"></div><div class="web-actions"><button class="btn btn-outline" id="web-order-invoice">Invoice</button><button class="btn btn-outline" id="web-order-chat">Message pharmacy</button><button class="btn btn-outline" id="web-order-refund">Request refund</button></div></div></dialog>
<dialog class="web-dialog" id="web-chat-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Healthcare conversation</h2><button class="icon-button" data-close type="button">×</button></div><div id="web-chat-messages" style="max-height:420px;overflow:auto"></div><form id="web-chat-form" style="display:flex;gap:8px"><input name="conversation_id" type="hidden"><input name="text" placeholder="Write a message" required><button class="btn btn-dark">Send</button></form></div></dialog>

<script>window.initCustomerWebMap=window.initCustomerWebMap||function(){window.__aimedixMapsReady=true};</script>
<script src="/assets/medical-web.js" defer></script>
<?php if ($browserMapsKey !== ''): ?><script async src="https://maps.googleapis.com/maps/api/js?key=<?= rawurlencode($browserMapsKey) ?>&libraries=geometry&loading=async&callback=initCustomerWebMap"></script><?php endif; ?>
