<main class="web-app" id="partner-web-app">
  <section class="web-app-header"><div><span class="pill">Healthcare partner workspace</span><h1>Manage your AIMEDIX practice.</h1><p>Pharmacy orders and prescriptions, laboratory appointments and reports, or doctor consultations—all in one role-aware portal.</p></div><div class="web-actions"><a class="btn btn-outline" href="/partner/register">Register</a><button class="btn btn-orange" id="partner-logout" type="button" hidden>Sign out</button></div></section>
  <div id="partner-global-status" aria-live="polite"></div>
  <section id="partner-login-panel" class="web-card" style="max-width:560px;margin:28px auto"><h2>Partner sign in</h2><form id="partner-login-form" style="display:grid;gap:13px"><label>Partner type<select name="provider_type"><option value="pharmacy">Pharmacy</option><option value="lab">Laboratory</option><option value="doctor">Doctor</option></select></label><label>Phone number<input name="phone" inputmode="tel" autocomplete="tel" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="btn btn-dark" type="submit">Sign in securely</button></form></section>
  <section id="partner-dashboard" hidden>
    <nav class="web-tabs"><button class="web-tab active" data-tab="dashboard">Dashboard</button><button class="web-tab" data-tab="tasks">Tasks</button><button class="web-tab" data-tab="catalog">Catalog</button><button class="web-tab" data-tab="messages">Messages</button><button class="web-tab" data-tab="patients">Patients</button><button class="web-tab" data-tab="account">Account</button></nav>
    <div class="web-panel active" data-panel="dashboard"><h2 id="partner-welcome">Dashboard</h2><div class="web-stats" id="partner-stats"></div><div class="web-card"><h3>What needs attention</h3><div id="partner-summary"></div></div></div>
    <div class="web-panel" data-panel="tasks"><h2 id="partner-task-title">Tasks</h2><div id="partner-tasks"></div><h2 id="partner-order-title" hidden>Medicine orders</h2><div id="partner-orders"></div></div>
    <div class="web-panel" data-panel="catalog"><div class="web-row"><div><h2 id="partner-catalog-title">Catalog</h2><p id="partner-catalog-copy"></p></div><button class="btn btn-dark" id="partner-add-catalog" type="button">Add item</button></div><div id="partner-catalog"></div></div>
    <div class="web-panel" data-panel="messages"><div class="web-row"><div><h2>Patient messages</h2><p>All medical conversations connected to your assigned work.</p></div><button class="btn btn-outline" id="partner-refresh-messages" type="button">Refresh</button></div><div id="partner-messages"></div></div>
    <div class="web-panel" data-panel="patients"><h2>Patients</h2><div id="partner-patients"></div></div>
    <div class="web-panel" data-panel="account"><h2>Account settings</h2><form id="partner-profile-form" class="web-card" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px"><label>Name<input name="name" required></label><label>Business / clinic<input name="business_name"></label><label>Email<input name="email" type="email"></label><label>City<input name="city"></label><label style="grid-column:1/-1">Address<input name="address"></label><label style="grid-column:1/-1">Description<textarea name="description"></textarea></label><label>Opening hours<input name="opening_hours"></label><label data-role="doctor">Speciality<input name="speciality"></label><label data-role="doctor">Qualification<input name="qualification"></label><label data-role="doctor">Consultation fee<input name="consultation_fee" type="number" min="0" step=".01"></label><label>New password (optional)<input name="password" type="password" minlength="8"></label><button class="btn btn-dark" style="grid-column:1/-1" type="submit">Save account</button></form></div>
  </section>
</main>
<dialog class="web-dialog" id="partner-catalog-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2 id="partner-catalog-dialog-title">Add item</h2><button class="icon-button" data-close type="button">×</button></div><form id="partner-catalog-form" style="display:grid;gap:12px"><input name="id" type="hidden"><label>Name<input name="name" required></label><label data-kind="pharmacy">SKU <span style="display:flex;gap:8px"><input name="sku"><button class="btn btn-outline" id="partner-generate-sku" type="button">Generate</button></span></label><label data-kind="pharmacy">Unit<input name="unit" value="strip"></label><label data-kind="pharmacy">Medicine type<select name="medicine_type"><option value="otc">OTC</option><option value="prescription_required">Prescription required</option><option value="restricted">Restricted</option></select></label><label data-kind="lab">Test code<input name="code"></label><label>Price<input name="price" type="number" min="0" step=".01" required></label><label data-kind="pharmacy">Stock<input name="stock" type="number" min="0" value="0"></label><label data-kind="lab">Report time (hours)<input name="report_hours" type="number" min="1" value="24"></label><label>Description<textarea name="description"></textarea></label><label data-kind="lab"><input name="home_collection" type="checkbox" style="width:auto"> Home collection available</label><button class="btn btn-dark" type="submit">Save item</button></form></div></dialog>
<dialog class="web-dialog" id="partner-chat-dialog"><div class="web-dialog-inner"><div class="web-dialog-head"><h2>Patient conversation</h2><button class="icon-button" data-close type="button">×</button></div><div id="partner-chat-messages" style="max-height:420px;overflow:auto"></div><form id="partner-chat-form" style="display:flex;gap:8px"><input name="conversation_id" type="hidden"><input name="text" placeholder="Write a message" required><button class="btn btn-dark" type="submit">Send</button></form></div></dialog>
<script src="/assets/partner-web.js" defer></script>
