import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Stack } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import Ionicons from '@expo/vector-icons/Ionicons';
import api from '@/api/axios';

type Method = { id: number; label: string; upi_id: string; is_default: boolean };
export default function PaymentMethodsScreen() {
  const [items, setItems] = useState<Method[]>([]); const [upiId, setUpiId] = useState(''); const [label, setLabel] = useState('Personal UPI'); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const { data } = await api.get('/users/me/payment-methods'); setItems(data.paymentMethods || []); } catch (e: any) { Alert.alert('Could not load payment methods', e?.response?.data?.message || 'Try again.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const add = async () => { if (!upiId.trim()) return Alert.alert('UPI ID required', 'Enter your UPI ID.'); setSaving(true); try { await api.post('/users/me/payment-methods', { upiId: upiId.trim(), label: label.trim() || 'UPI' }); setUpiId(''); await load(); } catch (e: any) { Alert.alert('Could not save UPI ID', e?.response?.data?.message || 'Try again.'); } finally { setSaving(false); } };
  const makeDefault = async (item: Method) => { try { const { data } = await api.patch(`/users/me/payment-methods/${item.id}/default`); setItems(data.paymentMethods || []); } catch (e: any) { Alert.alert('Could not update', e?.response?.data?.message || 'Try again.'); } };
  const remove = (item: Method) => Alert.alert('Remove payment method?', item.upi_id, [{ text: 'Cancel', style: 'cancel' }, { text: 'Remove', style: 'destructive', onPress: async () => { try { await api.delete(`/users/me/payment-methods/${item.id}`); await load(); } catch (e: any) { Alert.alert('Could not remove', e?.response?.data?.message || 'Try again.'); } } }]);
  return <SafeAreaView style={s.safe}><Stack.Screen options={{ title: 'Payment Methods', headerShown: true }} /><FlatList data={items} keyExtractor={(m) => String(m.id)} contentContainerStyle={s.body} ListHeaderComponent={<><Text style={s.hint}>Manage your saved UPI IDs. Card details are never stored in this app.</Text><View style={s.form}><Text style={s.title}>Add UPI ID</Text><TextInput style={s.input} placeholder="Label (e.g. Personal UPI)" value={label} onChangeText={setLabel} /><TextInput style={s.input} placeholder="name@bank" autoCapitalize="none" keyboardType="email-address" value={upiId} onChangeText={setUpiId} /><TouchableOpacity style={s.button} onPress={add} disabled={saving}>{saving ? <ActivityIndicator color="#111" /> : <Text style={s.buttonText}>Save UPI ID</Text>}</TouchableOpacity></View><Text style={s.title}>Saved methods</Text>{loading && <ActivityIndicator color="#111" />}</>} ListEmptyComponent={!loading ? <Text style={s.empty}>No UPI IDs saved.</Text> : null} renderItem={({ item }) => <View style={s.row}><View style={s.icon}><Ionicons name="phone-portrait-outline" size={20} color="#111" /></View><View style={{ flex: 1 }}><Text style={s.methodName}>{item.label}{item.is_default ? '  ·  Default' : ''}</Text><Text style={s.upi}>{item.upi_id}</Text></View>{!item.is_default && <TouchableOpacity onPress={() => makeDefault(item)} style={s.action}><Text style={s.actionText}>Set default</Text></TouchableOpacity>}<TouchableOpacity onPress={() => remove(item)} style={{ padding: 7 }}><Ionicons name="trash-outline" size={19} color="#DC2626" /></TouchableOpacity></View>} /></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#fff' }, body: { padding: 18 }, hint: { color: '#777', fontSize: 13, lineHeight: 19, marginBottom: 16 }, form: { borderWidth: 1, borderColor: '#eee', borderRadius: 16, padding: 16, marginBottom: 24 }, title: { fontSize: 17, fontWeight: '800', color: '#111', marginBottom: 12 }, input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 11, height: 46, paddingHorizontal: 12, marginBottom: 10, color: '#111' }, button: { minHeight: 46, borderRadius: 11, backgroundColor: '#FACC15', alignItems: 'center', justifyContent: 'center' }, buttonText: { fontWeight: '800', color: '#111' }, empty: { textAlign: 'center', color: '#888', padding: 20 }, row: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#eee' }, icon: { height: 42, width: 42, borderRadius: 12, backgroundColor: '#f5f5f5', alignItems: 'center', justifyContent: 'center' }, methodName: { fontWeight: '800', color: '#111' }, upi: { color: '#777', fontSize: 12, marginTop: 4 }, action: { padding: 6 }, actionText: { color: '#7c5c00', fontWeight: '700', fontSize: 11 } });
