import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Stack, router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import Ionicons from '@expo/vector-icons/Ionicons';
import api from '@/api/axios';
import { onLocationPicked } from '../ride/locationBus';

type Place = { id: number; label: 'HOME' | 'WORK' | 'OTHER'; name: string; address: string; lat?: number | null; lng?: number | null };
export default function SavedPlacesScreen() {
  const [places, setPlaces] = useState<Place[]>([]); const [loading, setLoading] = useState(true); const [label, setLabel] = useState<Place['label']>('HOME'); const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [lat, setLat] = useState<number | null>(null); const [lng, setLng] = useState<number | null>(null); const [editingId, setEditingId] = useState<number | null>(null); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const { data } = await api.get('/users/me/places'); setPlaces(data.places || []); } catch (e: any) { Alert.alert('Could not load places', e?.response?.data?.message || 'Try again.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => onLocationPicked('saved-place', (location) => { setLat(location.latitude); setLng(location.longitude); setAddress(location.address || `${location.latitude.toFixed(6)}, ${location.longitude.toFixed(6)}`); }), []);
  const add = async () => { if (!name.trim() || !address.trim()) return Alert.alert('Details required', 'Enter a place name and select its location on the map.'); if (lat == null || lng == null) return Alert.alert('Choose location', 'Use the map button to pin this place.'); setSaving(true); try { const payload = { label, name: name.trim(), address: address.trim(), lat, lng }; if (editingId) await api.patch(`/users/me/places/${editingId}`, payload); else await api.post('/users/me/places', payload); setName(''); setAddress(''); setLat(null); setLng(null); setEditingId(null); await load(); } catch (e: any) { Alert.alert('Could not save place', e?.response?.data?.message || 'Try again.'); } finally { setSaving(false); } };
  const edit = (place: Place) => { setEditingId(place.id); setLabel(place.label); setName(place.name); setAddress(place.address); setLat(place.lat == null ? null : Number(place.lat)); setLng(place.lng == null ? null : Number(place.lng)); };
  const remove = (place: Place) => Alert.alert('Delete saved place?', place.name, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: async () => { try { await api.delete(`/users/me/places/${place.id}`); setPlaces((all) => all.filter((p) => p.id !== place.id)); } catch (e: any) { Alert.alert('Could not delete', e?.response?.data?.message || 'Try again.'); } } }]);
  return <SafeAreaView style={s.safe}><Stack.Screen options={{ title: 'Saved Places', headerShown: true }} /><FlatList data={places} keyExtractor={(p) => String(p.id)} contentContainerStyle={s.body} ListHeaderComponent={<><Text style={s.hint}>Save your common destinations for quicker bookings.</Text><View style={s.card}><Text style={s.heading}>{editingId ? 'Edit saved place' : 'Add a place'}</Text><View style={s.labels}>{(['HOME', 'WORK', 'OTHER'] as const).map((v) => <TouchableOpacity key={v} onPress={() => setLabel(v)} style={[s.chip, label === v && s.activeChip]}><Text style={[s.chipText, label === v && s.activeText]}>{v}</Text></TouchableOpacity>)}</View><TextInput style={s.input} placeholder="Place name (e.g. Home)" value={name} onChangeText={setName} /><TouchableOpacity style={s.mapButton} onPress={() => router.push('/ride/map-picker?type=saved-place')}><Ionicons name="map-outline" size={18} color="#111" /><Text style={s.mapText}>{lat == null ? 'Choose place on map' : 'Change pinned location'}</Text></TouchableOpacity><TextInput style={[s.input, s.address]} placeholder="Select a location on the map" value={address} editable={false} multiline /><TouchableOpacity style={s.button} onPress={add} disabled={saving}>{saving ? <ActivityIndicator color="#111" /> : <Text style={s.buttonText}>{editingId ? 'Save changes' : 'Save place'}</Text>}</TouchableOpacity>{editingId ? <TouchableOpacity style={s.cancel} onPress={() => { setEditingId(null); setName(''); setAddress(''); setLat(null); setLng(null); }}><Text style={s.cancelText}>Cancel editing</Text></TouchableOpacity> : null}</View><Text style={s.heading}>Your places</Text>{loading && <ActivityIndicator color="#111" />}</>} ListEmptyComponent={!loading ? <Text style={s.empty}>No places saved yet.</Text> : null} renderItem={({ item }) => <View style={s.row}><View style={s.placeIcon}><Ionicons name={item.label === 'HOME' ? 'home-outline' : item.label === 'WORK' ? 'briefcase-outline' : 'location-outline'} size={20} color="#111" /></View><View style={{ flex: 1 }}><Text style={s.placeName}>{item.name} <Text style={s.placeLabel}>· {item.label}</Text></Text><Text style={s.placeAddress}>{item.address}</Text></View><TouchableOpacity onPress={() => edit(item)} style={{ padding: 6 }}><Ionicons name="create-outline" size={20} color="#555" /></TouchableOpacity><TouchableOpacity onPress={() => remove(item)} style={{ padding: 6 }}><Ionicons name="trash-outline" size={20} color="#DC2626" /></TouchableOpacity></View>} /></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#fff' }, body: { padding: 18, paddingBottom: 36 }, hint: { color: '#777', marginBottom: 16 }, card: { borderWidth: 1, borderColor: '#eee', borderRadius: 16, padding: 16, marginBottom: 24 }, heading: { fontSize: 17, fontWeight: '800', color: '#111', marginBottom: 12 }, labels: { flexDirection: 'row', gap: 8, marginBottom: 12 }, chip: { borderWidth: 1, borderColor: '#ddd', borderRadius: 18, paddingVertical: 7, paddingHorizontal: 13 }, activeChip: { backgroundColor: '#FACC15', borderColor: '#FACC15' }, chipText: { color: '#555', fontWeight: '700', fontSize: 12 }, activeText: { color: '#111' }, input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 11, paddingHorizontal: 12, minHeight: 46, marginBottom: 10, color: '#111' }, address: { minHeight: 70, textAlignVertical: 'top', paddingTop: 12 }, mapButton: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: '#ddd', borderRadius: 11, height: 44, paddingHorizontal: 12, marginBottom: 10 }, mapText: { color: '#111', fontWeight: '700', fontSize: 13 }, button: { backgroundColor: '#FACC15', borderRadius: 11, minHeight: 46, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: '#111', fontWeight: '800' }, cancel: { alignItems: 'center', paddingTop: 12 }, cancelText: { color: '#777', fontWeight: '700' }, empty: { color: '#888', textAlign: 'center', padding: 24 }, row: { flexDirection: 'row', gap: 7, alignItems: 'center', borderBottomWidth: 1, borderBottomColor: '#eee', paddingVertical: 15 }, placeIcon: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#f5f5f5', alignItems: 'center', justifyContent: 'center' }, placeName: { fontWeight: '800', color: '#111' }, placeLabel: { fontWeight: '500', color: '#777' }, placeAddress: { color: '#777', fontSize: 12, marginTop: 4 } });
