import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Stack } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import api from '@/api/axios';

type Ticket = { id: number; subject: string; description: string; category: string; status: string; resolution?: string | null; created_at: string };
const CATEGORIES = ['GENERAL', 'PAYMENT', 'RIDE', 'ACCOUNT', 'SAFETY'];
export default function SupportScreen() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [subject, setSubject] = useState(''); const [description, setDescription] = useState(''); const [category, setCategory] = useState('GENERAL'); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false);
  const load = useCallback(async () => { try { const { data } = await api.get('/complaints/mine'); setTickets(data.complaints || []); } catch (e: any) { Alert.alert('Support unavailable', e?.response?.data?.message || 'Please try again.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const submit = async () => { if (subject.trim().length < 4 || description.trim().length < 10) return Alert.alert('More details needed', 'Enter a subject (at least 4 characters) and details (at least 10 characters).'); setSending(true); try { await api.post('/complaints', { subject: subject.trim(), description: description.trim(), category, priority: 'MEDIUM' }); setSubject(''); setDescription(''); Alert.alert('Request sent', 'Support has received your request. You can track its status here.'); await load(); } catch (e: any) { Alert.alert('Could not send request', e?.response?.data?.message || 'Try again.'); } finally { setSending(false); } };
  return <SafeAreaView style={s.safe}><Stack.Screen options={{ title: 'Help & Support', headerShown: true }} /><FlatList data={tickets} keyExtractor={(t) => String(t.id)} contentContainerStyle={s.body} ListHeaderComponent={<><Text style={s.hint}>Send our support team a message and check replies here.</Text><View style={s.form}><Text style={s.title}>New support request</Text><TextInput style={s.input} placeholder="What do you need help with?" value={subject} onChangeText={setSubject} maxLength={200} /><Text style={s.label}>Category</Text><View style={s.categories}>{CATEGORIES.map((v) => <TouchableOpacity key={v} style={[s.chip, category === v && s.active]} onPress={() => setCategory(v)}><Text style={[s.chipText, category === v && s.activeText]}>{v}</Text></TouchableOpacity>)}</View><TextInput style={[s.input, s.message]} placeholder="Describe the issue (include a ride number if relevant)" value={description} onChangeText={setDescription} multiline maxLength={4000} /><TouchableOpacity style={s.button} onPress={submit} disabled={sending}>{sending ? <ActivityIndicator color="#111" /> : <Text style={s.buttonText}>Send request</Text>}</TouchableOpacity></View><Text style={s.title}>Your requests</Text>{loading && <ActivityIndicator color="#111" />}</>} ListEmptyComponent={!loading ? <Text style={s.empty}>You have not contacted support yet.</Text> : null} renderItem={({ item }) => <View style={s.ticket}><View style={s.ticketHead}><Text style={s.subject}>#{item.id} · {item.subject}</Text><Text style={s.status}>{item.status.replace('_', ' ')}</Text></View><Text style={s.meta}>{item.category} · {new Date(item.created_at).toLocaleDateString()}</Text><Text style={s.description}>{item.description}</Text>{item.resolution ? <Text style={s.reply}>Support: {item.resolution}</Text> : null}</View>} /></SafeAreaView>;
}
const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#fff' }, body: { padding: 18, paddingBottom: 36 }, hint: { color: '#777', marginBottom: 14 }, form: { borderWidth: 1, borderColor: '#eee', borderRadius: 16, padding: 15, marginBottom: 24 }, title: { fontSize: 17, fontWeight: '800', color: '#111', marginBottom: 12 }, input: { borderWidth: 1, borderColor: '#ddd', borderRadius: 11, minHeight: 46, paddingHorizontal: 12, marginBottom: 12, color: '#111' }, message: { minHeight: 100, textAlignVertical: 'top', paddingTop: 12 }, label: { fontSize: 12, fontWeight: '700', color: '#555', marginBottom: 7 }, categories: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 12 }, chip: { paddingVertical: 6, paddingHorizontal: 9, borderRadius: 15, borderWidth: 1, borderColor: '#ddd' }, active: { backgroundColor: '#FACC15', borderColor: '#FACC15' }, chipText: { fontSize: 10, color: '#555', fontWeight: '700' }, activeText: { color: '#111' }, button: { minHeight: 46, borderRadius: 11, backgroundColor: '#FACC15', alignItems: 'center', justifyContent: 'center' }, buttonText: { fontWeight: '800', color: '#111' }, empty: { textAlign: 'center', color: '#888', padding: 18 }, ticket: { borderWidth: 1, borderColor: '#eee', borderRadius: 14, padding: 14, marginBottom: 10 }, ticketHead: { flexDirection: 'row', justifyContent: 'space-between', gap: 8 }, subject: { flex: 1, color: '#111', fontWeight: '800' }, status: { color: '#725400', fontSize: 11, fontWeight: '800' }, meta: { color: '#888', fontSize: 11, marginTop: 6 }, description: { color: '#555', fontSize: 13, lineHeight: 19, marginTop: 10 }, reply: { color: '#176b45', backgroundColor: '#ecfdf5', padding: 10, borderRadius: 9, marginTop: 10, fontSize: 12, lineHeight: 18 } });
